version: "3.4"

services:
  app:
    # container_name: php-81-fpm-dev
    build: .
    image: tiagofranca/php-81-mysql-dev:22-06-17
    links:
      - db
    depends_on:
      - db
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
      - COMPOSER_HOME=/home/www/.composer
      - MY_ENV="myValue"
      - ENV_KEY
    restart: "unless-stopped"
    ports:
      - ${HTTP_PORT:-8000}:8000
      # - ${FPM_PORT:-9000}:9000
    volumes:
      - ${APP_PATH:-./}:/var/www/app
      # https://getcomposer.org/doc/06-config.md#cache-dir
      - ${COMPOSER_HOME:-~/.composer}:/home/www/.composer
      - /tmp:/host-tmp
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: ${PHP_MEMORY_LIMITS_PATH:-512M}
            reservations:
                memory: ${PHP_MEMORY_RESERVATIONS_PATH:-512M}
    command: /bin/bash -c "${APP_RUN_COMMAND:-php -S 0.0.0.0:8000 -t /var/www/app}"

  db:
    image: mariadb:10
    environment:
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_DATABASE=${DB_DATABASE:-mysql}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./db_data:/etc/mysql/conf.d
